
# ------------------------------------ INSTALLATION VARIABLES ------------------------------------
PLUGIN_NAME = 'KIHARALAB'
KIHARALAB_VERSION = '1.0.1'
dmm_GIT = 'https://github.com/dmm'
dmm_HOME = 'KIHARA_HOME'
DMM_HOME = 'DMM_HOME'


# Supported versions
V1_0 = '1.0'

# Plugin version
dmm_VERSION = '1.0.1'

# Protocol versions 
DMM_DEFAULT_VERSION = V1_0


# Protocol repo versions
DMM_REPO_DEFAULT_VERSION = V1_0

cryoread_GIT = 'https://github.com/cryoread/'
cryoread_HOME = 'KIHARA_HOME'
CRYOREAD_HOME = 'CRYOREAD_HOME'

# Supported versions
V1_0 = '1.0'

# Plugin version
cryoread_VERSION = '1.0.1'

# Protocol versions
CRYOREAD_DEFAULT_VERSION = V1_0

# Protocol repo versions
CRYOREAD_REPO_DEFAULT_VERSION = V1_0


DAQ_HOME = 'DAQ_HOME'
EMAP2SEC_HOME = 'EMAP2SEC_HOME'
MAINMAST_HOME = 'MAINMAST_HOME'

DAQ_DEFAULT_VERSION = V1_0
EMAP2SEC_DEFAULT_VERSION = V1_0
MAINMAST_DEFAULT_VERSION = V1_0

# Protocol repo versions
DAQ_REPO_DEFAULT_VERSION = V1_0
EMAP2SEC_REPO_DEFAULT_VERSION = V1_0
EMAP2SECPLUS_REPO_DEFAULT_VERSION = V1_0
MAINMAST_REPO_DEFAULT_VERSION = V1_0

# ------------------------------------ PROTOCOL FORM VARIABLES ------------------------------------
# Emap2sec param constants
EMAP2SEC_NORM_GLOBAL = 0
EMAP2SEC_NORM_LOCAL = 1
EMAP2SEC_TYPE_EMAP2SEC = 0
EMAP2SEC_TYPE_EMAP2SECPLUS = 1
# Emap2sec+ form constants
EMAP2SECPLUS_TYPE_SIMUL6A = 0
EMAP2SECPLUS_TYPE_SIMUL10A = 1
EMAP2SECPLUS_TYPE_SIMUL6_10A = 2
EMAP2SECPLUS_TYPE_EXPERIMENTAL = 3
EMAP2SECPLUS_MODE_DETECT_STRUCTS = 0
EMAP2SECPLUS_MODE_DETECT_EVALUATE_STRUCTS = 1
EMAP2SECPLUS_MODE_DETECT_DNA = 2
EMAP2SECPLUS_FOLD1 = 0
EMAP2SECPLUS_FOLD2 = 1
EMAP2SECPLUS_FOLD3 = 2
EMAP2SECPLUS_FOLD4 = 3
# Emap2sec+ param constants
EMAP2SECPLUS_MODE_DETECT_EXPERIMENTAL_FOLD4 = 2
EMAP2SECPLUS_MODE_DETECT_EVALUATE_EXPERIMENTAL_FOLD4 = 3
EMAP2SECPLUS_MODE_DETECT_DNA_EXPERIMENTAL_FOLD4 = 4